language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
  - "12"
before_script:
  - git config --global core.autocrlf false
  - git config --global user.email "your@gmail.com"
  - git config --global user.name "your name"
before_install: npm install --global sort-package-json
script:  npm link && mkdir stash && cd stash && tslib init mylib && tslib init mylib && yarn && yarn build && yarn test
